import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App | Next JS | Rimon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {/* <h1 className="text-3xl font-bold underline">Hello world!</h1> */}
        <a href="">
          <img src="" alt="" />
          <h2 className="text-3xl font-bold">Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores,
            eius distinctio odio amet sequi excepturi dicta nemo, cum dolorem
            iure incidunt, esse earum delectus optio consequuntur assumenda
            voluptates omnis est.
          </p>
        </a>
        <a href="">
          <img src="" alt="" />
          <h2 className="text-3xl font-bold">Events in San francisco</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores,
            eius distinctio odio amet sequi excepturi dicta nemo, cum dolorem
            iure incidunt, esse earum delectus optio consequuntur assumenda
            voluptates omnis est.
          </p>
        </a>
        <a href="">
          <img src="" alt="" />
          <h2 className="text-3xl font-bold">Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores,
            eius distinctio odio amet sequi excepturi dicta nemo, cum dolorem
            iure incidunt, esse earum delectus optio consequuntur assumenda
            voluptates omnis est.
          </p>
        </a>
      </main>

      {/* <footer className={styles.footer}> */}
      <footer className="footer footer-center p-4 bg-base-300 text-base-content">
        <div>
          <p>Copyright © 2022 - All rights reserved by Ltd</p>
        </div>
      </footer>
      {/* </footer> */}
    </div>
  );
}
